# Generated by Django 4.2.5 on 2023-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
